(111, 'Connection refused'); first exception - None","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-11T14:14:04.980Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-11T14:14:04.980Z","msg":"Error when connecting to server","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-7","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-11T14:14:06.904Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140028787123968,"pri":"ERROR","tname":"Thread-5","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-01-11T14:14:07.026Z","msg":"Socket failed to connect: <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.242', 55592)>; error=111 (Connection refused)","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-11T14:14:07.027Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-11T14:14:07.027Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-11T14:14:07.027Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-11T14:14:07.027Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-11T14:14:07.027Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-11T14:14:07.028Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-11T14:14:07.028Z","msg":"Error when connecting to server","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-9","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-11T14:14:09.074Z","msg":"Socket failed to connect: <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.242', 55600)>; error=111 (Connection refused)","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-11T14:14:09.075Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-11T14:14:09.075Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-11T14:14:09.075Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-11T14:14:09.075Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-11T14:14:09.075Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-11T14:14:09.076Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-11T14:14:09.076Z","msg":"Error when connecting to server","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-11","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-11T14:14:11.122Z","msg":"Socket failed to connect: <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.242', 55602)>; error=111 (Connection refused)","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-11T14:14:11.123Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-11T14:14:11.123Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-11T14:14:11.123Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-11T14:14:11.123Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-11T14:14:11.123Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-11T14:14:11.124Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-11T14:14:11.124Z","msg":"Error when connecting to server","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-13","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-11T14:14:11.909Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140028787123968,"pri":"ERROR","tname":"Thread-5","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-01-11T14:14:13.171Z","msg":"Socket failed to connect: <socket.socket fd=20, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.242', 55612)>; error=111 (Connection refused)","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-15","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-11T14:14:13.172Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-15","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-11T14:14:13.172Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-15","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-11T14:14:13.172Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-15","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-11T14:14:13.172Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-15","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-11T14:14:13.172Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-15","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-11T14:14:13.172Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-15","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-11T14:14:13.173Z","msg":"Error when connecting to server","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-15","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-11T14:14:15.218Z","msg":"Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.242', 55620)>; error=111 (Connection refused)","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-17","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-{"time":"2023-12-14T10:09:22.835Z","msg":"Configuration: {'general.ready_file_path': '/var/run/ericsson/alarm-proxy/ready', 'general.server_id': 'localhost', 'messaging.server_url': 'amqp://guest:guest@rabbitmq-ha:5672/?heartbeat=30', 'proxy.maxRedisMissedMessage': '1000', 'proxy.monitoringDelay': '10', 'proxy.redisHost': 'redis', 'proxy.redisKeepCnt': 3, 'proxy.redisKeepIdle': 10, 'proxy.redisKeepIntvl': 10, 'proxy.redisPort': '6379', 'proxy.redisReconnectionDelay': '1', 'proxy.redisSocket': '/var/opt/ericsson/alarm-proxy/ericsson-alarm-proxy.sock', 'proxy.redisTimeout': '-1', 'proxy.redisUserTimeout': 38, 'proxy.resync_enabled': 'True', 'proxy.resync_interval': '30', 'proxy.resync_scope': 'mksp1', 'time.readiness_interval': '5'}","pid":1,"tid":140668770394368,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":367}}
{"time":"2023-12-14T10:09:22.835Z","msg":"Connection to redis by IP","pid":1,"tid":140668770394368,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":380}}
{"time":"2023-12-14T10:09:22.875Z","msg":"Connected to redis","pid":1,"tid":140668770394368,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":420}}
{"time":"2023-12-14T10:09:22.876Z","msg":"Setting up RabbitMQ connection","pid":1,"tid":140668770394368,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":422}}
{"time":"2023-12-14T10:09:22.883Z","msg":"Running subscription loop","pid":1,"tid":140668567549696,"pri":"INFO","tname":"Thread-3","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":241}}
{"time":"2023-12-14T10:09:22.888Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140668542371584,"pri":"ERROR","tname":"Thread-6","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2023-12-14T10:09:22.942Z","msg":"Connection opened","pid":1,"tid":140668659545856,"pri":"INFO","tname":"Thread-1","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":123}}
{"time":"2024-01-02T08:59:10.392Z","msg":"Configuration: {'general.ready_file_path': '/var/run/ericsson/alarm-proxy/ready', 'general.server_id': 'localhost', 'messaging.server_url': 'amqp://guest:guest@rabbitmq-ha:5672/?heartbeat=30', 'proxy.maxRedisMissedMessage': '1000', 'proxy.monitoringDelay': '10', 'proxy.redisHost': 'redis', 'proxy.redisKeepCnt': 3, 'proxy.redisKeepIdle': 10, 'proxy.redisKeepIntvl': 10, 'proxy.redisPort': '6379', 'proxy.redisReconnectionDelay': '1', 'proxy.redisSocket': '/var/opt/ericsson/alarm-proxy/ericsson-alarm-proxy.sock', 'proxy.redisTimeout': '-1', 'proxy.redisUserTimeout': 38, 'proxy.resync_enabled': 'True', 'proxy.resync_interval': '30', 'proxy.resync_scope': 'mksp1', 'time.readiness_interval': '5'}","pid":1,"tid":140279854096640,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":367}}
{"time":"2024-01-02T08:59:10.392Z","msg":"Connection to redis by IP","pid":1,"tid":140279854096640,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":380}}
{"time":"2024-01-02T08:59:14.470Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":140279854096640,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-02T08:59:23.683Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":140279854096640,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-02T08:59:25.730Z","msg":"Couldn't connect to redis. Retrying after 5.0 seconds.","pid":1,"tid":140279854096640,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-02T08:59:31.745Z","msg":"Couldn't connect to redis. Retrying after 15.0 seconds.","pid":1,"tid":140279854096640,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-02T08:59:46.760Z","msg":"Connected to redis","pid":1,"tid":140279854096640,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":420}}
{"time":"2024-01-02T08:59:46.761Z","msg":"Setting up RabbitMQ connection","pid":1,"tid":140279854096640,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":422}}
{"time":"2024-01-02T08:59:46.762Z","msg":"Running subscription loop","pid":1,"tid":140279726462720,"pri":"INFO","tname":"Thread-3","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":241}}
{"time":"2024-01-02T08:59:46.763Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140279709677312,"pri":"ERROR","tname":"Thread-5","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-01-02T08:59:46.767Z","msg":"Connection opened","pid":1,"tid":140279743248128,"pri":"INFO","tname":"Thread-1","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":123}}
{"time":"2024-01-11T14:13:29.153Z","msg":"Configuration: {'general.ready_file_path': '/var/run/ericsson/alarm-proxy/ready', 'general.server_id': 'localhost', 'messaging.server_url': 'amqp://guest:guest@rabbitmq-ha:5672/?heartbeat=30', 'proxy.maxRedisMissedMessage': '1000', 'proxy.monitoringDelay': '10', 'proxy.redisHost': 'redis', 'proxy.redisKeepCnt': 3, 'proxy.redisKeepIdle': 10, 'proxy.redisKeepIntvl': 10, 'proxy.redisPort': '6379', 'proxy.redisReconnectionDelay': '1', 'proxy.redisSocket': '/var/opt/ericsson/alarm-proxy/ericsson-alarm-proxy.sock', 'proxy.redisTimeout': '-1', 'proxy.redisUserTimeout': 38, 'proxy.resync_enabled': 'True', 'proxy.resync_interval': '30', 'proxy.resync_scope': 'mksp1', 'time.readiness_interval': '5'}","pid":1,"tid":140028931543296,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":367}}
{"time":"2024-01-11T14:13:29.154Z","msg":"Connection to redis by IP","pid":1,"tid":140028931543296,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":380}}
{"time":"2024-01-11T14:13:34.839Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":140028931543296,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-11T14:13:35.841Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":140028931543296,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-11T14:13:41.865Z","msg":"Couldn't connect to redis. Retrying after 5.0 seconds.","pid":1,"tid":140028931543296,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-11T14:13:46.876Z","msg":"Couldn't connect to redis. Retrying after 15.0 seconds.","pid":1,"tid":140028931543296,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-11T14:14:01.892Z","msg":"Connected to redis","pid":1,"tid":140028931543296,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":420}}
{"time":"2024-01-11T14:14:01.892Z","msg":"Setting up RabbitMQ connection","pid":1,"tid":140028931543296,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":422}}
{"time":"2024-01-11T14:14:01.896Z","msg":"Running subscription loop","pid":1,"tid":140028803909376,"pri":"INFO","tname":"Thread-3","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":241}}
{"time":"2024-01-11T14:14:01.898Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140028787123968,"pri":"ERROR","tname":"Thread-5","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-01-11T14:14:02.930Z","msg":"Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.242', 59518)>; error=111 (Connection refused)","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-11T14:14:02.931Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-11T14:14:02.931Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-11T14:14:02.931Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-11T14:14:02.931Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-11T14:14:02.932Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-11T14:14:02.932Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-11T14:14:02.932Z","msg":"Error when connecting to server","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-1","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-11T14:14:04.978Z","msg":"Socket failed to connect: <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.242', 59532)>; error=111 (Connection refused)","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-11T14:14:04.979Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-11T14:14:04.979Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-11T14:14:04.979Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-11T14:14:04.979Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140028778731264,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-11T14:14:04.979Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedErrorproxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-11T14:14:15.219Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-17","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-11T14:14:15.219Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-17","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-11T14:14:15.219Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-17","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-11T14:14:15.219Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-17","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-11T14:14:15.219Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-17","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-11T14:14:15.220Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-17","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-11T14:14:15.220Z","msg":"Error when connecting to server","pid":1,"tid":140028820694784,"pri":"ERROR","tname":"Thread-17","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-11T14:14:16.914Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140028787123968,"pri":"ERROR","tname":"Thread-5","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-01-11T14:14:17.270Z","msg":"Connection opened","pid":1,"tid":140028778731264,"pri":"INFO","tname":"Thread-19","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":123}}
{"time":"2024-01-12T14:08:03.245Z","msg":"Configuration: {'general.ready_file_path': '/var/run/ericsson/alarm-proxy/ready', 'general.server_id': 'localhost', 'messaging.server_url': 'amqp://guest:guest@rabbitmq-ha:5672/?heartbeat=30', 'proxy.maxRedisMissedMessage': '1000', 'proxy.monitoringDelay': '10', 'proxy.redisHost': 'redis', 'proxy.redisKeepCnt': 3, 'proxy.redisKeepIdle': 10, 'proxy.redisKeepIntvl': 10, 'proxy.redisPort': '6379', 'proxy.redisReconnectionDelay': '1', 'proxy.redisSocket': '/var/opt/ericsson/alarm-proxy/ericsson-alarm-proxy.sock', 'proxy.redisTimeout': '-1', 'proxy.redisUserTimeout': 38, 'proxy.resync_enabled': 'True', 'proxy.resync_interval': '30', 'proxy.resync_scope': 'mksp1', 'time.readiness_interval': '5'}","pid":1,"tid":139646204674304,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":367}}
{"time":"2024-01-12T14:08:03.246Z","msg":"Connection to redis by IP","pid":1,"tid":139646204674304,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":380}}
{"time":"2024-01-12T14:08:08.365Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":139646204674304,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-12T14:08:14.509Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":139646204674304,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-12T14:08:20.645Z","msg":"Couldn't connect to redis. Retrying after 5.0 seconds.","pid":1,"tid":139646204674304,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-12T14:08:26.659Z","msg":"Couldn't connect to redis. Retrying after 15.0 seconds.","pid":1,"tid":139646204674304,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-12T14:08:41.674Z","msg":"Connected to redis","pid":1,"tid":139646204674304,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":420}}
{"time":"2024-01-12T14:08:41.674Z","msg":"Setting up RabbitMQ connection","pid":1,"tid":139646204674304,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":422}}
{"time":"2024-01-12T14:08:41.678Z","msg":"Running subscription loop","pid":1,"tid":139646077040384,"pri":"INFO","tname":"Thread-3","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":241}}
{"time":"2024-01-12T14:08:41.680Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":139646060254976,"pri":"ERROR","tname":"Thread-5","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-01-12T14:08:41.684Z","msg":"Connection opened","pid":1,"tid":139646093825792,"pri":"INFO","tname":"Thread-1","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":123}}
{"time":"2024-01-23T04:28:47.387Z","msg":"Configuration: {'general.ready_file_path': '/var/run/ericsson/alarm-proxy/ready', 'general.server_id': 'localhost', 'messaging.server_url': 'amqp://guest:guest@rabbitmq-ha:5672/?heartbeat=30', 'proxy.maxRedisMissedMessage': '1000', 'proxy.monitoringDelay': '10', 'proxy.redisHost': 'redis', 'proxy.redisKeepCnt': 3, 'proxy.redisKeepIdle': 10, 'proxy.redisKeepIntvl': 10, 'proxy.redisPort': '6379', 'proxy.redisReconnectionDelay': '1', 'proxy.redisSocket': '/var/opt/ericsson/alarm-proxy/ericsson-alarm-proxy.sock', 'proxy.redisTimeout': '-1', 'proxy.redisUserTimeout': 38, 'proxy.resync_enabled': 'True', 'proxy.resync_interval': '30', 'proxy.resync_scope': 'mksp1', 'time.readiness_interval': '5'}","pid":1,"tid":140236063805696,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":367}}
{"time":"2024-01-23T04:28:47.387Z","msg":"Connection to redis by IP","pid":1,"tid":140236063805696,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":380}}
{"time":"2024-01-23T04:28:53.530Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":140236063805696,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-23T04:28:59.674Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":140236063805696,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-23T04:29:05.819Z","msg":"Couldn't connect to redis. Retrying after 5.0 seconds.","pid":1,"tid":140236063805696,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-23T04:29:11.837Z","msg":"Couldn't connect to redis. Retrying after 15.0 seconds.","pid":1,"tid":140236063805696,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-23T04:29:26.853Z","msg":"Connected to redis","pid":1,"tid":140236063805696,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":420}}
{"time":"2024-01-23T04:29:26.853Z","msg":"Setting up RabbitMQ connection","pid":1,"tid":140236063805696,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":422}}
{"time":"2024-01-23T04:29:26.858Z","msg":"Running subscription loop","pid":1,"tid":140235936171776,"pri":"INFO","tname":"Thread-3","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":241}}
{"time":"2024-01-23T04:29:26.859Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140235715376896,"pri":"ERROR","tname":"Thread-5","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-01-23T04:29:27.896Z","msg":"Socket failed to connect: <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.161', 59836)>; error=111 (Connection refused)","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-23T04:29:27.896Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-23T04:29:27.896Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-23T04:29:27.897Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-23T04:29:27.897Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-23T04:29:27.897Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-23T04:29:27.897Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-23T04:29:27.897Z","msg":"Error when connecting to server","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-1","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-23T04:29:29.944Z","msg":"Socket failed to connect: <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.161', 59852)>; error=111 (Connection refused)","pid":1,"tid":140235706984192,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-23T04:29:29.944Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140235706984192,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-23T04:29:29.944Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140235706984192,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-23T04:29:29.944Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140235706984192,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-23T04:29:29.945Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140235706984192,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-23T04:29:29.945Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140235706984192,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-23T04:29:29.945Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140235706984192,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-23T04:29:29.945Z","msg":"Error when connecting to server","pid":1,"tid":140235706984192,"pri":"ERROR","tname":"Thread-7","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-23T04:29:31.866Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140235715376896,"pri":"ERROR","tname":"Thread-5","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-01-23T04:29:31.992Z","msg":"Socket failed to connect: <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.161', 59868)>; error=111 (Connection refused)","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-23T04:29:31.992Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-23T04:29:31.993Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-23T04:29:31.993Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-23T04:29:31.993Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-23T04:29:31.993Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-23T04:29:31.993Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-23T04:29:31.994Z","msg":"Error when connecting to server","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-9","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-23T04:29:34.040Z","msg":"Socket failed to connect: <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.161', 59880)>; error=111 (Connection refused)","pid":1,"tid":140235706984192,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-23T04:29:34.040Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140235706984192,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-23T04:29:34.040Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140235706984192,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-23T04:29:34.040Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140235706984192,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-23T04:29:34.041Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140235706984192,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-23T04:29:34.041Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140235706984192,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-23T04:29:34.041Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140235706984192,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-23T04:29:34.041Z","msg":"Error when connecting to server","pid":1,"tid":140235706984192,"pri":"ERROR","tname":"Thread-11","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-23T04:29:36.088Z","msg":"Socket failed to connect: <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.161', 59882)>; error=111 (Connection refused)","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-23T04:29:36.088Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-23T04:29:36.088Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-23T04:29:36.088Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-23T04:29:36.088Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-23T04:29:36.089Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-23T04:29:36.089Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-23T04:29:36.089Z","msg":"Error when connecting to server","pid":1,"tid":140235952957184,"pri":"ERROR","tname":"Thread-13","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-23T04:29:36.871Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140235715376896,"pri":"ERROR","tname":"Thread-5","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-01-23T04:29:38.139Z","msg":"Connection opened","pid":1,"tid":140235706984192,"pri":"INFO","tname":"Thread-15","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":123}}
{"time":"2024-01-25T13:22:07.194Z","msg":"Configuration: {'general.ready_file_path': '/var/run/ericsson/alarm-proxy/ready', 'general.server_id': 'localhost', 'messaging.server_url': 'amqp://guest:guest@rabbitmq-ha:5672/?heartbeat=30', 'proxy.maxRedisMissedMessage': '1000', 'proxy.monitoringDelay': '10', 'proxy.redisHost': 'redis', 'proxy.redisKeepCnt': 3, 'proxy.redisKeepIdle': 10, 'proxy.redisKeepIntvl': 10, 'proxy.redisPort': '6379', 'proxy.redisReconnectionDelay': '1', 'proxy.redisSocket': '/var/opt/ericsson/alarm-proxy/ericsson-alarm-proxy.sock', 'proxy.redisTimeout': '-1', 'proxy.redisUserTimeout': 38, 'proxy.resync_enabled': 'True', 'proxy.resync_interval': '30', 'proxy.resync_scope': 'mksp1', 'time.readiness_interval': '5'}","pid":1,"tid":140132794409216,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":367}}
{"time":"2024-01-25T13:22:07.194Z","msg":"Connection to redis by IP","pid":1,"tid":140132794409216,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":380}}
{"time":"2024-01-25T13:22:12.646Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":140132794409216,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-25T13:22:20.721Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":140132794409216,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-25T13:22:21.722Z","msg":"Couldn't connect to redis. Retrying after 5.0 seconds.","pid":1,"tid":140132794409216,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-25T13:22:26.727Z","msg":"Couldn't connect to redis. Retrying after 15.0 seconds.","pid":1,"tid":140132794409216,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-25T13:22:41.743Z","msg":"Connected to redis","pid":1,"tid":140132794409216,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":420}}
{"time":"2024-01-25T13:22:41.743Z","msg":"Setting up RabbitMQ connection","pid":1,"tid":140132794409216,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":422}}
{"time":"2024-01-25T13:22:41.745Z","msg":"Running subscription loop","pid":1,"tid":140132666775296,"pri":"INFO","tname":"Thread-3","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":241}}
{"time":"2024-01-25T13:22:41.746Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140132649989888,"pri":"ERROR","tname":"Thread-5","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-01-25T13:22:42.781Z","msg":"Socket failed to connect: <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.51', 35020)>; error=111 (Connection refused)","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-25T13:22:42.782Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-25T13:22:42.782Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-25T13:22:42.782Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-25T13:22:42.782Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-25T13:22:42.782Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-25T13:22:42.783Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-25T13:22:42.783Z","msg":"Error when connecting to server","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-1","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-25T13:22:44.828Z","msg":"Socket failed to connect: <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.51', 35024)>; error=111 (Connection refused)","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-25T13:22:44.829Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-25T13:22:44.829Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-25T13:22:44.829Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-25T13:22:44.829Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-25T13:22:44.829Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-25T13:22:44.829Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-25T13:22:44.830Z","msg":"Error when connecting to server","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-7","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-25T13:22:46.750Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140132649989888,"pri":"ERROR","tname":"Thread-5","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-01-25T13:22:46.876Z","msg":"Socket failed to connect: <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.51', 35034)>; error=111 (Connection refused)","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-25T13:22:46.877Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-25T13:22:46.877Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-25T13:22:46.877Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-25T13:22:46.877Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-25T13:22:46.877Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-25T13:22:46.877Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-25T13:22:46.877Z","msg":"Error when connecting to server","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-9","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-25T13:22:48.925Z","msg":"Socket failed to connect: <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.51', 35048)>; error=111 (Connection refused)","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-25T13:22:48.926Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-25T13:22:48.926Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-25T13:22:48.926Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-25T13:22:48.926Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-25T13:22:48.926Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-25T13:22:48.926Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-25T13:22:48.927Z","msg":"Error when connecting to server","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-11","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-25T13:22:50.972Z","msg":"Socket failed to connect: <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.51', 54454)>; error=111 (Connection refused)","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-25T13:22:50.972Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-25T13:22:50.973Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-25T13:22:50.973Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-25T13:22:50.973Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-25T13:22:50.973Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-25T13:22:50.973Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-13","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-25T13:22:50.973Z","msg":"Error when connecting to server","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-13","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-25T13:22:51.755Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140132649989888,"pri":"ERROR","tname":"Thread-5","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-01-25T13:22:53.021Z","msg":"Socket failed to connect: <socket.socket fd=20, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.51', 54460)>; error=111 (Connection refused)","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-15","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-25T13:22:53.022Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-15","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-25T13:22:53.022Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-15","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-25T13:22:53.022Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-15","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-25T13:22:53.022Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-15","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-25T13:22:53.022Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-15","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-25T13:22:53.022Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-15","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-25T13:22:53.023Z","msg":"Error when connecting to server","pid":1,"tid":140132300617472,"pri":"ERROR","tname":"Thread-15","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-25T13:22:55.068Z","msg":"Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.51', 54472)>; error=111 (Connection refused)","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-17","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-25T13:22:55.068Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-17","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-25T13:22:55.069Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-17","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-25T13:22:55.069Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-17","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-25T13:22:55.069Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-17","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-25T13:22:55.069Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-17","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-25T13:22:55.069Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-17","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-25T13:22:55.069Z","msg":"Error when connecting to server","pid":1,"tid":140132683560704,"pri":"ERROR","tname":"Thread-17","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-25T13:22:56.760Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140132649989888,"pri":"ERROR","tname":"Thread-5","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-01-25T13:22:57.121Z","msg":"Connection opened","pid":1,"tid":140132300617472,"pri":"INFO","tname":"Thread-19","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":123}}
{"time":"2024-01-30T10:39:37.253Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":140569597583616,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-30T10:39:43.395Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":140569597583616,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-30T10:39:45.379Z","msg":"Couldn't connect to redis. Retrying after 5.0 seconds.","pid":1,"tid":140569597583616,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-30T10:39:51.395Z","msg":"Couldn't connect to redis. Retrying after 15.0 seconds.","pid":1,"tid":140569597583616,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-01-30T10:40:06.411Z","msg":"Connected to redis","pid":1,"tid":140569597583616,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":420}}
{"time":"2024-01-30T10:40:06.412Z","msg":"Setting up RabbitMQ connection","pid":1,"tid":140569597583616,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":422}}
{"time":"2024-01-30T10:40:06.414Z","msg":"Running subscription loop","pid":1,"tid":140569469949696,"pri":"INFO","tname":"Thread-3","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":241}}
{"time":"2024-01-30T10:40:06.416Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140569461556992,"pri":"ERROR","tname":"Thread-6","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-01-30T10:40:07.459Z","msg":"Socket failed to connect: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.19', 43946)>; error=111 (Connection refused)","pid":1,"tid":140569486735104,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-30T10:40:07.459Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140569486735104,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-30T10:40:07.460Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140569486735104,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-30T10:40:07.460Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140569486735104,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-30T10:40:07.460Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140569486735104,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-30T10:40:07.460Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140569486735104,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-30T10:40:07.460Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140569486735104,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-30T10:40:07.461Z","msg":"Error when connecting to server","pid":1,"tid":140569486735104,"pri":"ERROR","tname":"Thread-1","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-30T10:40:09.507Z","msg":"Socket failed to connect: <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.19', 43960)>; error=111 (Connection refused)","pid":1,"tid":140569238038272,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-30T10:40:09.507Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140569238038272,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-30T10:40:09.507Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140569238038272,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-30T10:40:09.508Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140569238038272,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-30T10:40:09.508Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140569238038272,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-30T10:40:09.508Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140569238038272,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-30T10:40:09.508Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140569238038272,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-30T10:40:09.508Z","msg":"Error when connecting to server","pid":1,"tid":140569238038272,"pri":"ERROR","tname":"Thread-7","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-30T10:40:11.422Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140569461556992,"pri":"ERROR","tname":"Thread-6","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-01-30T10:40:11.555Z","msg":"Socket failed to connect: <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.19', 43964)>; error=111 (Connection refused)","pid":1,"tid":140569486735104,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-30T10:40:11.555Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140569486735104,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-30T10:40:11.556Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140569486735104,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-30T10:40:11.556Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140569486735104,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-30T10:40:11.556Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140569486735104,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-30T10:40:11.556Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140569486735104,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-30T10:40:11.556Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140569486735104,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-30T10:40:11.556Z","msg":"Error when connecting to server","pid":1,"tid":140569486735104,"pri":"ERROR","tname":"Thread-9","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-30T10:40:13.604Z","msg":"Socket failed to connect: <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.19', 43970)>; error=111 (Connection refused)","pid":1,"tid":140569238038272,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-01-30T10:40:13.604Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140569238038272,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-01-30T10:40:13.604Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140569238038272,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-01-30T10:40:13.605Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140569238038272,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-01-30T10:40:13.605Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140569238038272,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-01-30T10:40:13.605Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140569238038272,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-01-30T10:40:13.605Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140569238038272,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-01-30T10:40:13.605Z","msg":"Error when connecting to server","pid":1,"tid":140569238038272,"pri":"ERROR","tname":"Thread-11","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-01-30T10:40:14.610Z","msg":"Connection opened","pid":1,"tid":140569486735104,"pri":"INFO","tname":"Thread-13","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":123}}
{"time":"2024-02-01T20:59:03.811Z","msg":"Configuration: {'general.ready_file_path': '/var/run/ericsson/alarm-proxy/ready', 'general.server_id': 'localhost', 'messaging.server_url': 'amqp://guest:guest@rabbitmq-ha:5672/?heartbeat=30', 'proxy.maxRedisMissedMessage': '1000', 'proxy.monitoringDelay': '10', 'proxy.redisHost': 'redis', 'proxy.redisKeepCnt': 3, 'proxy.redisKeepIdle': 10, 'proxy.redisKeepIntvl': 10, 'proxy.redisPort': '6379', 'proxy.redisReconnectionDelay': '1', 'proxy.redisSocket': '/var/opt/ericsson/alarm-proxy/ericsson-alarm-proxy.sock', 'proxy.redisTimeout': '-1', 'proxy.redisUserTimeout': 38, 'proxy.resync_enabled': 'True', 'proxy.resync_interval': '30', 'proxy.resync_scope': 'mksp1', 'time.readiness_interval': '5'}","pid":1,"tid":139964226498816,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":367}}
{"time":"2024-02-01T20:59:03.811Z","msg":"Connection to redis by IP","pid":1,"tid":139964226498816,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":380}}
{"time":"2024-02-01T20:59:08.056Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":139964226498816,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-02-01T20:59:14.205Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":139964226498816,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-02-01T20:59:18.294Z","msg":"Couldn't connect to redis. Retrying after 5.0 seconds.","pid":1,"tid":139964226498816,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-02-01T20:59:24.436Z","msg":"Couldn't connect to redis. Retrying after 15.0 seconds.","pid":1,"tid":139964226498816,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-02-01T20:59:39.452Z","msg":"Connected to redis","pid":1,"tid":139964226498816,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":420}}
{"time":"2024-02-01T20:59:39.453Z","msg":"Setting up RabbitMQ connection","pid":1,"tid":139964226498816,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":422}}
{"time":"2024-02-01T20:59:39.457Z","msg":"Running subscription loop","pid":1,"tid":139964098864896,"pri":"INFO","tname":"Thread-3","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":241}}
{"time":"2024-02-01T20:59:39.458Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":139964082079488,"pri":"ERROR","tname":"Thread-5","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-02-01T20:59:40.500Z","msg":"Socket failed to connect: <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.228', 49402)>; error=111 (Connection refused)","pid":1,"tid":139964115650304,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-02-01T20:59:40.501Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":139964115650304,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-02-01T20:59:40.501Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":139964115650304,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-02-01T20:59:40.501Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":139964115650304,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-02-01T20:59:40.501Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":139964115650304,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-02-01T20:59:40.501Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":139964115650304,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-02-01T20:59:40.502Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":139964115650304,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-02-01T20:59:40.502Z","msg":"Error when connecting to server","pid":1,"tid":139964115650304,"pri":"ERROR","tname":"Thread-1","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-02-01T20:59:42.548Z","msg":"Socket failed to connect: <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.228', 49404)>; error=111 (Connection refused)","pid":1,"tid":139964073686784,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-02-01T20:59:42.549Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":139964073686784,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-02-01T20:59:42.549Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":139964073686784,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-02-01T20:59:42.549Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":139964073686784,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-02-01T20:59:42.549Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":139964073686784,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-02-01T20:59:42.549Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":139964073686784,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-02-01T20:59:42.549Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":139964073686784,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-02-01T20:59:42.550Z","msg":"Error when connecting to server","pid":1,"tid":139964073686784,"pri":"ERROR","tname":"Thread-7","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-02-01T20:59:43.554Z","msg":"Connection opened","pid":1,"tid":139964115650304,"pri":"INFO","tname":"Thread-9","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":123}}
{"msg":", 'proxy.maxRedisMissedMessage': '1000', 'proxy.monitoringDelay': '10', 'proxy.redisHost': 'redis', 'proxy.redisKeepCnt': 3, 'proxy.redisKeepIdle': 10, 'proxy.redisKeepIntvl': 10, 'proxy.redisPort': '6379', 'proxy.redisReconnectionDelay': '1', 'proxy.redisSocket': '/var/opt/ericsson/alarm-proxy/ericsson-alarm-proxy.sock', 'proxy.redisTimeout': '-1', 'proxy.redisUserTimeout': 38, 'proxy.resync_enabled': 'True', 'proxy.resync_interval': '30', 'proxy.resync_scope': 'mksp1', 'time.readiness_interval': '5'}\", \"pid\": 1, \"tid\": 140335713624320, \"pri\": \"INFO\", \"tname\": \"MainThread\", \"subsys\": \"ericsson.alarm.proxy.app\", \"host\": \"alarm-proxy-6888785644-mnxjl\", \"pname\": \"alarm-proxy\", \"file\": {\"name\": \"app.py\", \"line\": 367}}"}
{"time":"2024-02-06T08:36:02.756Z","msg":"Connection to redis by IP","pid":1,"tid":140335713624320,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":380}}
{"time":"2024-02-06T08:36:08.835Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":140335713624320,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-02-06T08:36:14.970Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":140335713624320,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-02-06T08:36:15.985Z","msg":"Couldn't connect to redis. Retrying after 5.0 seconds.","pid":1,"tid":140335713624320,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-02-06T08:36:20.992Z","msg":"Couldn't connect to redis. Retrying after 15.0 seconds.","pid":1,"tid":140335713624320,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-02-06T08:36:36.007Z","msg":"Couldn't connect to redis. Retrying after 30.0 seconds.","pid":1,"tid":140335713624320,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-02-06T08:37:06.038Z","msg":"Connected to redis","pid":1,"tid":140335713624320,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":420}}
{"time":"2024-02-06T08:37:06.038Z","msg":"Setting up RabbitMQ connection","pid":1,"tid":140335713624320,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":422}}
{"time":"2024-02-06T08:37:06.040Z","msg":"Running subscription loop","pid":1,"tid":140335585990400,"pri":"INFO","tname":"Thread-3","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":241}}
{"time":"2024-02-06T08:37:06.041Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140335363647232,"pri":"ERROR","tname":"Thread-5","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-02-06T08:37:06.045Z","msg":"Connection opened","pid":1,"tid":140335602775808,"pri":"INFO","tname":"Thread-1","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":123}}
{"time":"2024-02-06T13:28:24.622Z","msg":"Configuration: {'general.ready_file_path': '/var/run/ericsson/alarm-proxy/ready', 'general.server_id': 'localhost', 'messaging.server_url': 'amqp://guest:guest@rabbitmq-ha:5672/?heartbeat=30', 'proxy.maxRedisMissedMessage': '1000', 'proxy.monitoringDelay': '10', 'proxy.redisHost': 'redis', 'proxy.redisKeepCnt': 3, 'proxy.redisKeepIdle': 10, 'proxy.redisKeepIntvl': 10, 'proxy.redisPort': '6379', 'proxy.redisReconnectionDelay': '1', 'proxy.redisSocket': '/var/opt/ericsson/alarm-proxy/ericsson-alarm-proxy.sock', 'proxy.redisTimeout': '-1', 'proxy.redisUserTimeout': 38, 'proxy.resync_enabled': 'True', 'proxy.resync_interval': '30', 'proxy.resync_scope': 'mksp1', 'time.readiness_interval': '5'}","pid":1,"tid":140277660881152,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":367}}
{"time":"2024-02-06T13:28:24.622Z","msg":"Connection to redis by IP","pid":1,"tid":140277660881152,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":380}}
{"time":"2024-02-06T13:28:28.317Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":140277660881152,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-02-06T13:28:32.387Z","msg":"Couldn't connect to redis. Retrying after 1.0 seconds.","pid":1,"tid":140277660881152,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-02-06T13:28:34.438Z","msg":"Couldn't connect to redis. Retrying after 5.0 seconds.","pid":1,"tid":140277660881152,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-02-06T13:28:40.519Z","msg":"Couldn't connect to redis. Retrying after 15.0 seconds.","pid":1,"tid":140277660881152,"pri":"WARN","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":410}}
{"time":"2024-02-06T13:28:55.534Z","msg":"Connected to redis","pid":1,"tid":140277660881152,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":420}}
{"time":"2024-02-06T13:28:55.535Z","msg":"Setting up RabbitMQ connection","pid":1,"tid":140277660881152,"pri":"INFO","tname":"MainThread","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":422}}
{"time":"2024-02-06T13:28:55.539Z","msg":"Running subscription loop","pid":1,"tid":140277533247232,"pri":"INFO","tname":"Thread-3","subsys":"ericsson.alarm.proxy.app","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":241}}
{"time":"2024-02-06T13:28:55.540Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140277314479872,"pri":"ERROR","tname":"Thread-5","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-02-06T13:28:56.579Z","msg":"Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.166', 50100)>; error=111 (Connection refused)","pid":1,"tid":140277550032640,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-02-06T13:28:56.579Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140277550032640,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-02-06T13:28:56.579Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140277550032640,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-02-06T13:28:56.579Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140277550032640,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-02-06T13:28:56.580Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140277550032640,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-02-06T13:28:56.580Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140277550032640,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-02-06T13:28:56.580Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140277550032640,"pri":"ERROR","tname":"Thread-1","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-02-06T13:28:56.580Z","msg":"Error when connecting to server","pid":1,"tid":140277550032640,"pri":"ERROR","tname":"Thread-1","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-02-06T13:28:58.626Z","msg":"Socket failed to connect: <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.166', 50102)>; error=111 (Connection refused)","pid":1,"tid":140277306087168,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-02-06T13:28:58.626Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140277306087168,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-02-06T13:28:58.626Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140277306087168,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-02-06T13:28:58.626Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140277306087168,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-02-06T13:28:58.626Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140277306087168,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-02-06T13:28:58.627Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140277306087168,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-02-06T13:28:58.627Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140277306087168,"pri":"ERROR","tname":"Thread-7","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-02-06T13:28:58.627Z","msg":"Error when connecting to server","pid":1,"tid":140277306087168,"pri":"ERROR","tname":"Thread-7","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-02-06T13:29:00.547Z","msg":"Unable to contact one of the resources this service depends on","pid":1,"tid":140277314479872,"pri":"ERROR","tname":"Thread-5","subsys":"ericsson.alarm.proxy.app","exc_info":"Traceback (most recent call last):\n  File \"/src/ericsson/alarm/proxy/app.py\", line 296, in is_ready\n    if not publisher.get_channel().is_open:\nAttributeError: 'NoneType' object has no attribute 'is_open'","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"app.py","line":300}}
{"time":"2024-02-06T13:29:00.674Z","msg":"Socket failed to connect: <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.166', 50104)>; error=111 (Connection refused)","pid":1,"tid":140277550032640,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-02-06T13:29:00.674Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140277550032640,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-02-06T13:29:00.674Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140277550032640,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-02-06T13:29:00.674Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140277550032640,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-02-06T13:29:00.674Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140277550032640,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-02-06T13:29:00.675Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140277550032640,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-02-06T13:29:00.675Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140277550032640,"pri":"ERROR","tname":"Thread-9","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-02-06T13:29:00.675Z","msg":"Error when connecting to server","pid":1,"tid":140277550032640,"pri":"ERROR","tname":"Thread-9","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-02-06T13:29:02.722Z","msg":"Socket failed to connect: <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.42.0.166', 50120)>; error=111 (Connection refused)","pid":1,"tid":140277306087168,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.io_services_utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"io_services_utils.py","line":349}}
{"time":"2024-02-06T13:29:02.722Z","msg":"TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.43.4.55', 5672))","pid":1,"tid":140277306087168,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":375}}
{"time":"2024-02-06T13:29:02.722Z","msg":"AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')","pid":1,"tid":140277306087168,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":291}}
{"time":"2024-02-06T13:29:02.722Z","msg":"AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.","pid":1,"tid":140277306087168,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":746}}
{"time":"2024-02-06T13:29:02.722Z","msg":"AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140277306087168,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.utils.connection_workflow","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"connection_workflow.py","line":723}}
{"time":"2024-02-06T13:29:02.723Z","msg":"Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None","pid":1,"tid":140277306087168,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":327}}
{"time":"2024-02-06T13:29:02.723Z","msg":"Self-initiated stack bring-up failed: AMQPConnectionError: (AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None,)","pid":1,"tid":140277306087168,"pri":"ERROR","tname":"Thread-11","subsys":"pika.adapters.base_connection","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"base_connection.py","line":357}}
{"time":"2024-02-06T13:29:02.723Z","msg":"Error when connecting to server","pid":1,"tid":140277306087168,"pri":"ERROR","tname":"Thread-11","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":140}}
{"time":"2024-02-06T13:29:03.731Z","msg":"Connection opened","pid":1,"tid":140277550032640,"pri":"INFO","tname":"Thread-13","subsys":"ericsson.alarm.proxy.utils","host":"alarm-proxy-6888785644-mnxjl","pname":"alarm-proxy","file":{"name":"utils.py","line":123}}
