_switch"}
{}
{"time":"2023-12-14T10:09:28.586Z","msg":"Connected to amqp://guest:**@rabbitmq-ha:5672//","pid":1,"tid":139657408180480,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.connection","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"connection.py","line":22}}
{"time":"2023-12-14T10:09:28.592Z","msg":"mingle: searching for neighbors","pid":1,"tid":139657408180480,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":40}}
{"time":"2023-12-14T10:09:29.657Z","msg":"mingle: all alone","pid":1,"tid":139657408180480,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":49}}
{"time":"2023-12-14T10:09:30.123Z","msg":"celery@failover-api-7d57484775-88b45 ready.","pid":1,"tid":139657408180480,"pri":"INFO","tname":"MainThread","subsys":"celery.apps.worker","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"worker.py","line":176}}
{"time":"2023-12-14T10:09:38.993Z","msg":"sync with celery@unified-ui-55796949fc-wgqst","pid":1,"tid":139657408180480,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.control","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"control.py","line":310}}
{"time":"2023-12-14T10:28:28.394Z","msg":"sync with celery@failover-api-7d57484775-hh6mr","pid":1,"tid":139657408180480,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.control","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"control.py","line":310}}
{"time":"2023-12-14T10:28:39.217Z","msg":"sync with celery@unified-ui-55796949fc-cj79d","pid":1,"tid":139657408180480,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.control","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"control.py","line":310}}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":" "}
{"log_msg":" -------------- celery@failover-api-7d57484775-88b45 v5.2.7 (dawn-chorus)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":"-- ******* ---- Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.28 2024-01-02 08:59:45"}
{"log_msg":"- *** --- * --- "}
{"log_msg":"- ** ---------- [config]"}
{"log_msg":"- ** ---------- .> app:         __main__:0x7f74a2c614f0"}
{"log_msg":"- ** ---------- .> transport:   amqp://guest:**@rabbitmq-ha:5672//"}
{"log_msg":"- ** ---------- .> results:     rpc://"}
{"log_msg":"- *** --- * --- .> concurrency: 8 (prefork)"}
{"log_msg":"-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":" -------------- [queues]"}
{"log_msg":"                .> celery_failover  exchange=celery_failover(direct) key=celery_failover"}
{"log_msg":"                "}
{}
{"log_msg":"[tasks]"}
{"log_msg":"  . ericsson.failover.tasks.failover.tasks.on_start_switch_error"}
{"log_msg":"  . ericsson.tasks.basic.switch_server"}
{"log_msg":"  . ericsson.tasks.basic.switch_service"}
{"log_msg":"  . ericsson.tasks.default.switch_server"}
{"log_msg":"  . ericsson.tasks.failover.do_switch"}
{}
{"time":"2024-01-02T08:59:46.147Z","msg":"Connected to amqp://guest:**@rabbitmq-ha:5672//","pid":1,"tid":140139074072832,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.connection","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"connection.py","line":22}}
{"time":"2024-01-02T08:59:46.152Z","msg":"mingle: searching for neighbors","pid":1,"tid":140139074072832,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":40}}
{"time":"2024-01-02T08:59:47.206Z","msg":"mingle: sync with 2 nodes","pid":1,"tid":140139074072832,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":43}}
{"time":"2024-01-02T08:59:47.206Z","msg":"mingle: sync complete","pid":1,"tid":140139074072832,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":47}}
{"time":"2024-01-02T08:59:47.247Z","msg":"celery@failover-api-7d57484775-88b45 ready.","pid":1,"tid":140139074072832,"pri":"INFO","tname":"MainThread","subsys":"celery.apps.worker","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"worker.py","line":176}}
{"time":"2024-01-02T08:59:51.884Z","msg":"sync with celery@unified-ui-55796949fc-wgqst","pid":1,"tid":140139074072832,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.control","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"control.py","line":310}}
{"time":"2024-01-04T04:47:15.391Z","msg":"missed heartbeat from celery@failover-api-7d57484775-hh6mr","pid":1,"tid":140139074072832,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.gossip","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"gossip.py","line":145}}
{"time":"2024-01-04T04:50:24.193Z","msg":"sync with celery@failover-api-7d57484775-hh6mr","pid":1,"tid":140139074072832,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.control","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"control.py","line":310}}
{"time":"2024-01-04T04:50:27.523Z","msg":"sync with celery@unified-ui-55796949fc-cj79d","pid":1,"tid":140139074072832,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.control","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"control.py","line":310}}
{"log_msg":"Could not connect to RabbitMQ: [Errno -3] Temporary failure in name resolution"}
{"log_msg":"Could not connect to RabbitMQ: [Errno -3] Temporary failure in name resolution"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":" "}
{"log_msg":" -------------- celery@failover-api-7d57484775-88b45 v5.2.7 (dawn-chorus)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":"-- ******* ---- Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.28 2024-01-11 14:14:19"}
{"log_msg":"- *** --- * --- "}
{"log_msg":"- ** ---------- [config]"}
{"log_msg":"- ** ---------- .> app:         __main__:0x7f09646ca4f0"}
{"log_msg":"- ** ---------- .> transport:   amqp://guest:**@rabbitmq-ha:5672//"}
{"log_msg":"- ** ---------- .> results:     rpc://"}
{"log_msg":"- *** --- * --- .> concurrency: 8 (prefork)"}
{"log_msg":"-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":" -------------- [queues]"}
{"log_msg":"                .> celery_failover  exchange=celery_failover(direct) key=celery_failover"}
{"log_msg":"                "}
{}
{"log_msg":"[tasks]"}
{"log_msg":"  . ericsson.failover.tasks.failover.tasks.on_start_switch_error"}
{"log_msg":"  . ericsson.tasks.basic.switch_server"}
{"log_msg":"  . ericsson.tasks.basic.switch_service"}
{"log_msg":"  . ericsson.tasks.default.switch_server"}
{"log_msg":"  . ericsson.tasks.failover.do_switch"}
{}
{"time":"2024-01-11T14:14:19.317Z","msg":"Connected to amqp://guest:**@rabbitmq-ha:5672//","pid":1,"tid":139678466515200,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.connection","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"connection.py","line":22}}
{"time":"2024-01-11T14:14:19.326Z","msg":"mingle: searching for neighbors","pid":1,"tid":139678466515200,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":40}}
{"time":"2024-01-11T14:14:20.348Z","msg":"mingle: all alone","pid":1,"tid":139678466515200,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":49}}
{"time":"2024-01-11T14:14:20.377Z","msg":"celery@failover-api-7d57484775-88b45 ready.","pid":1,"tid":139678466515200,"pri":"INFO","tname":"MainThread","subsys":"celery.apps.worker","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"worker.py","line":176}}
{"log_msg":"Could not connect to RabbitMQ: [Errno -3] Temporary failure in name resolution"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":" "}
{"log_msg":" -------------- celery@failover-api-7d57484775-88b45 v5.2.7 (dawn-chorus)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":"-- ******* ---- Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.28 2024-01-12 14:08:41"}
{"log_msg":"- *** --- * --- "}
{"log_msg":"- ** ---------- [config]"}
{"log_msg":"- ** ---------- .> app:         __main__:0x7ffbf03304f0"}
{"log_msg":"- ** ---------- .> transport:   amqp://guest:**@rabbitmq-ha:5672//"}
{"log_msg":"- ** ---------- .> results:     rpc://"}
{"log_msg":"- *** --- * --- .> concurrency: 8 (prefork)"}
{"log_msg":"-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":" -------------- [queues]"}
{"log_msg":"                .> celery_failover  exchange=celery_failover(direct) key=celery_failover"}
{"log_msg":"                "}
{}
{"log_msg":"[tasks]"}
{"log_msg":"  . ericsson.failover.tasks.failover.tasks.on_start_switch_error"}
{"log_msg":"  . ericsson.tasks.basic.switch_server"}
{"log_msg":"  . ericsson.tasks.basic.switch_service"}
{"log_msg":"  . ericsson.tasks.default.switch_server"}
{"log_msg":"  . ericsson.tasks.failover.do_switch"}
{}
{"time":"2024-01-12T14:08:42.119Z","msg":"Connected to amqp://guest:**@rabbitmq-ha:5672//","pid":1,"tid":140720193655040,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.connection","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"connection.py","line":22}}
{"time":"2024-01-12T14:08:42.123Z","msg":"mingle: searching for neighbors","pid":1,"tid":140720193655040,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":40}}
{"time":"2024-01-12T14:08:43.140Z","msg":"mingle: all alone","pid":1,"tid":140720193655040,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":49}}
{"time":"2024-01-12T14:08:43.174Z","msg":"celery@failover-api-7d57484775-88b45 ready.","pid":1,"tid":140720193655040,"pri":"INFO","tname":"MainThread","subsys":"celery.apps.worker","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"worker.py","line":176}}
{"log_msg":"Could not connect to RabbitMQ: [Errno -3] Temporary failure in name resolution"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":" "}
{"log_msg":" -------------- celery@failover-api-7d57484775-88b45 v5.2.7 (dawn-chorus)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":"-- ******* ---- Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.28 2024-01-23 04:29:40"}
{"log_msg":"- *** --- * --- "}
{"log_msg":"- ** ---------- [config]"}
{"log_msg":"- ** ---------- .> app:         __main__:0x7fbb2c38e4f0"}
{"log_msg":"- ** ---------- .> transport:   amqp://guest:**@rabbitmq-ha:5672//"}
{"log_msg":"- ** ---------- .> results:     rpc://"}
{"log_msg":"- *** --- * --- .> concurrency: 8 (prefork)"}
{"log_msg":"-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":" -------------- [queues]"}
{"log_msg":"                .> celery_failover  exchange=celery_failover(direct) key=celery_failover"}
{"log_msg":"                "}
{}
{"log_msg":"[tasks]"}
{"log_msg":"  . ericsson.failover.tasks.failover.tasks.on_start_switch_error"}
{"log_msg":"  . ericsson.tasks.basic.switch_server"}
{"log_msg":"  . ericsson.tasks.basic.switch_service"}
{"log_msg":"  . ericsson.tasks.default.switch_server"}
{"log_msg":"  . ericsson.tasks.failover.do_switch"}
{}
{"time":"2024-01-23T04:29:40.493Z","msg":"Connected to amqp://guest:**@rabbitmq-ha:5672//","pid":1,"tid":140442027786496,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.connection","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"connection.py","line":22}}
{"time":"2024-01-23T04:29:40.496Z","msg":"mingle: searching for neighbors","pid":1,"tid":140442027786496,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":40}}
{"time":"2024-01-23T04:29:41.527Z","msg":"mingle: all alone","pid":1,"tid":140442027786496,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":49}}
{"time":"2024-01-23T04:29:41.559Z","msg":"celery@failover-api-7d57484775-88b45 ready.","pid":1,"tid":140442027786496,"pri":"INFO","tname":"MainThread","subsys":"celery.apps.worker","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"worker.py","line":176}}
{"time":"2024-01-23T04:29:41.899Z","msg":"sync with celery@unified-ui-55796949fc-wgqst","pid":1,"tid":140442027786496,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.control","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"control.py","line":310}}
{"log_msg":"Could not connect to RabbitMQ: [Errno -3] Temporary failure in name resolution"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":" "}
{"log_msg":" -------------- celery@failover-api-7d57484775-88b45 v5.2.7 (dawn-chorus)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":"-- ******* ---- Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.28 2024-01-25 13:23:00"}
{"log_msg":"- *** --- * --- "}
{"log_msg":"- ** ---------- [config]"}
{"log_msg":"- ** ---------- .> app:         __main__:0x7f30f060f4f0"}
{"log_msg":"- ** ---------- .> transport:   amqp://guest:**@rabbitmq-ha:5672//"}
{"log_msg":"- ** ---------- .> results:     rpc://"}
{"log_msg":"- *** --- * --- .> concurrency: 8 (prefork)"}
{"log_msg":"-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":" -------------- [queues]"}
{"log_msg":"                .> celery_failover  exchange=celery_failover(direct) {"log_msg":" "}
{"log_msg":" -------------- celery@failover-api-7d57484775-88b45 v5.2.7 (dawn-chorus)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":"-- ******* ---- Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.28 2023-12-14 10:09:28"}
{"log_msg":"- *** --- * --- "}
{"log_msg":"- ** ---------- [config]"}
{"log_msg":"- ** ---------- .> app:         __main__:0x7f047d3fd4f0"}
{"log_msg":"- ** ---------- .> transport:   amqp://guest:**@rabbitmq-ha:5672//"}
{"log_msg":"- ** ---------- .> results:     rpc://"}
{"log_msg":"- *** --- * --- .> concurrency: 8 (prefork)"}
{"log_msg":"-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":" -------------- [queues]"}
{"log_msg":"                .> celery_failover  exchange=celery_failover(direct) key=celery_failover"}
{"log_msg":"                "}
{}
{"log_msg":"[tasks]"}
{"log_msg":"  . ericsson.failover.tasks.failover.tasks.on_start_switch_error"}
{"log_msg":"  . ericsson.tasks.basic.switch_server"}
{"log_msg":"  . ericsson.tasks.basic.switch_service"}
{"log_msg":"  . ericsson.tasks.default.switch_server"}
{"log_msg":"  . ericsson.tasks.failover.dokey=celery_failover"}
{"log_msg":"                "}
{}
{"log_msg":"[tasks]"}
{"log_msg":"  . ericsson.failover.tasks.failover.tasks.on_start_switch_error"}
{"log_msg":"  . ericsson.tasks.basic.switch_server"}
{"log_msg":"  . ericsson.tasks.basic.switch_service"}
{"log_msg":"  . ericsson.tasks.default.switch_server"}
{"log_msg":"  . ericsson.tasks.failover.do_switch"}
{}
{"time":"2024-01-25T13:23:01.001Z","msg":"Connected to amqp://guest:**@rabbitmq-ha:5672//","pid":1,"tid":139848318292224,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.connection","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"connection.py","line":22}}
{"time":"2024-01-25T13:23:01.006Z","msg":"mingle: searching for neighbors","pid":1,"tid":139848318292224,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":40}}
{"time":"2024-01-25T13:23:02.022Z","msg":"mingle: sync with 1 nodes","pid":1,"tid":139848318292224,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":43}}
{"time":"2024-01-25T13:23:02.023Z","msg":"mingle: sync complete","pid":1,"tid":139848318292224,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":47}}
{"time":"2024-01-25T13:23:02.051Z","msg":"celery@failover-api-7d57484775-88b45 ready.","pid":1,"tid":139848318292224,"pri":"INFO","tname":"MainThread","subsys":"celery.apps.worker","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"worker.py","line":176}}
{"log_msg":"Could not connect to RabbitMQ: [Errno -3] Temporary failure in name resolution"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":" "}
{"log_msg":" -------------- celery@failover-api-7d57484775-88b45 v5.2.7 (dawn-chorus)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":"-- ******* ---- Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.28 2024-01-30 10:40:14"}
{"log_msg":"- *** --- * --- "}
{"log_msg":"- ** ---------- [config]"}
{"log_msg":"- ** ---------- .> app:         __main__:0x7f21b114e4f0"}
{"log_msg":"- ** ---------- .> transport:   amqp://guest:**@rabbitmq-ha:5672//"}
{"log_msg":"- ** ---------- .> results:     rpc://"}
{"log_msg":"- *** --- * --- .> concurrency: 8 (prefork)"}
{"log_msg":"-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":" -------------- [queues]"}
{"log_msg":"                .> celery_failover  exchange=celery_failover(direct) key=celery_failover"}
{"log_msg":"                "}
{}
{"log_msg":"[tasks]"}
{"log_msg":"  . ericsson.failover.tasks.failover.tasks.on_start_switch_error"}
{"log_msg":"  . ericsson.tasks.basic.switch_server"}
{"log_msg":"  . ericsson.tasks.basic.switch_service"}
{"log_msg":"  . ericsson.tasks.default.switch_server"}
{"log_msg":"  . ericsson.tasks.failover.do_switch"}
{}
{"time":"2024-01-30T10:40:14.922Z","msg":"Connected to amqp://guest:**@rabbitmq-ha:5672//","pid":1,"tid":139782831833344,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.connection","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"connection.py","line":22}}
{"time":"2024-01-30T10:40:14.926Z","msg":"mingle: searching for neighbors","pid":1,"tid":139782831833344,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":40}}
{"time":"2024-01-30T10:40:15.944Z","msg":"mingle: all alone","pid":1,"tid":139782831833344,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":49}}
{"time":"2024-01-30T10:40:15.978Z","msg":"celery@failover-api-7d57484775-88b45 ready.","pid":1,"tid":139782831833344,"pri":"INFO","tname":"MainThread","subsys":"celery.apps.worker","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"worker.py","line":176}}
{"log_msg":"Could not connect to RabbitMQ: [Errno 113] No route to host"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":" "}
{"log_msg":" -------------- celery@failover-api-7d57484775-88b45 v5.2.7 (dawn-chorus)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":"-- ******* ---- Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.28 2024-02-01 20:59:43"}
{"log_msg":"- *** --- * --- "}
{"log_msg":"- ** ---------- [config]"}
{"log_msg":"- ** ---------- .> app:         __main__:0x7f14e1c924f0"}
{"log_msg":"- ** ---------- .> transport:   amqp://guest:**@rabbitmq-ha:5672//"}
{"log_msg":"- ** ---------- .> results:     rpc://"}
{"log_msg":"- *** --- * --- .> concurrency: 8 (prefork)"}
{"log_msg":"-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":" -------------- [queues]"}
{"log_msg":"                .> celery_failover  exchange=celery_failover(direct) key=celery_failover"}
{"log_msg":"                "}
{}
{"log_msg":"[tasks]"}
{"log_msg":"  . ericsson.failover.tasks.failover.tasks.on_start_switch_error"}
{"log_msg":"  . ericsson.tasks.basic.switch_server"}
{"log_msg":"  . ericsson.tasks.basic.switch_service"}
{"log_msg":"  . ericsson.tasks.default.switch_server"}
{"log_msg":"  . ericsson.tasks.failover.do_switch"}
{}
{"time":"2024-02-01T20:59:43.913Z","msg":"Connected to amqp://guest:**@rabbitmq-ha:5672//","pid":1,"tid":139727814336768,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.connection","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"connection.py","line":22}}
{"time":"2024-02-01T20:59:43.926Z","msg":"mingle: searching for neighbors","pid":1,"tid":139727814336768,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":40}}
{"time":"2024-02-01T20:59:44.943Z","msg":"mingle: all alone","pid":1,"tid":139727814336768,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":49}}
{"time":"2024-02-01T20:59:44.978Z","msg":"celery@failover-api-7d57484775-88b45 ready.","pid":1,"tid":139727814336768,"pri":"INFO","tname":"MainThread","subsys":"celery.apps.worker","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"worker.py","line":176}}
{"log_msg":"Could not connect to RabbitMQ: [Errno -3] Temporary failure in name resolution"}
{"log_msg":"Could not connect to RabbitMQ: [Errno -3] Temporary failure in name resolution"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":" "}
{"log_msg":" -------------- celery@failover-api-7d57484775-88b45 v5.2.7 (dawn-chorus)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":"-- ******* ---- Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.28 2024-02-06 08:37:00"}
{"log_msg":"- *** --- * --- "}
{"log_msg":"- ** ---------- [config]"}
{"log_msg":"- ** ---------- .> app:         __main__:0x7f4d95b6f4f0"}
{"log_msg":"- ** ---------- .> transport:   amqp://guest:**@rabbitmq-ha:5672//"}
{"log_msg":"- ** ---------- .> results:     rpc://"}
{"log_msg":"- *** --- * --- .> concurrency: 8 (prefork)"}
{"log_msg":"-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":" -------------- [queues]"}
{"log_msg":"                .> celery_failover  exchange=celery_failover(direct) key=celery_failover"}
{"log_msg":"                "}
{}
{"log_msg":"[tasks]"}
{"log_msg":"  . ericsson.failover.tasks.failover.tasks.on_start_switch_error"}
{"log_msg":"  . ericsson.tasks.basic.switch_server"}
{"log_msg":"  . ericsson.tasks.basic.switch_service"}
{"log_msg":"  . ericsson.tasks.default.switch_server"}
{"log_msg":"  . ericsson.tasks.failover.do_switch"}
{}
{"time":"2024-02-06T08:37:00.441Z","msg":"Connected to amqp://guest:**@rabbitmq-ha:5672//","pid":1,"tid":139971351212288,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.connection","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"connection.py","line":22}}
{"time":"2024-02-06T08:37:00.445Z","msg":"mingle: searching for neighbors","pid":1,"tid":139971351212288,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":40}}
{"time":"2024-02-06T08:37:01.463Z","msg":"mingle: all alone","pid":1,"tid":139971351212288,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":49}}
{"time":"2024-02-06T08:37:01.504Z","msg":"celery@failover-api-7d57484775-88b45 ready.","pid":1,"tid":139971351212288,"pri":"INFO","tname":"MainThread","subsys":"celery.apps.worker","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"worker.py","line":176}}
{"time":"2024-02-06T08:37:08.476Z","msg":"sync with celery@unified-ui-55796949fc-wgqst","pid":1,"tid":139971351212288,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.control","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"control.py","line":310}}
{"log_msg":"Could not connect to RabbitMQ: [Errno 113] No route to host"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":"Could not connect to RabbitMQ: [Errno 111] Connection refused"}
{"log_msg":" "}
{"log_msg":" -------------- celery@failover-api-7d57484775-88b45 v5.2.7 (dawn-chorus)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":"-- ******* ---- Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.28 2024-02-06 13:29:03"}
{"log_msg":"- *** --- * --- "}
{"log_msg":"- ** ---------- [config]"}
{"log_msg":"- ** ---------- .> app:         __main__:0x7f4ed1ced4f0"}
{"log_msg":"- ** ---------- .> transport:   amqp://guest:**@rabbitmq-ha:5672//"}
{"log_msg":"- ** ---------- .> results:     rpc://"}
{"log_msg":"- *** --- * --- .> concurrency: 8 (prefork)"}
{"log_msg":"-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)"}
{"log_msg":"--- ***** ----- "}
{"log_msg":" -------------- [queues]"}
{"log_msg":"                .> celery_failover  exchange=celery_failover(direct) key=celery_failover"}
{"log_msg":"                "}
{}
{"log_msg":"[tasks]"}
{"log_msg":"  . ericsson.failover.tasks.failover.tasks.on_start_switch_error"}
{"log_msg":"  . ericsson.tasks.basic.switch_server"}
{"log_msg":"  . ericsson.tasks.basic.switch_service"}
{"log_msg":"  . ericsson.tasks.default.switch_server"}
{"log_msg":"  . ericsson.tasks.failover.do_switch"}
{}
{"time":"2024-02-06T13:29:04.068Z","msg":"Connected to amqp://guest:**@rabbitmq-ha:5672//","pid":1,"tid":139976654377216,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.connection","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"connection.py","line":22}}
{"time":"2024-02-06T13:29:04.072Z","msg":"mingle: searching for neighbors","pid":1,"tid":139976654377216,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":40}}
{"time":"2024-02-06T13:29:05.092Z","msg":"mingle: all alone","pid":1,"tid":139976654377216,"pri":"INFO","tname":"MainThread","subsys":"celery.worker.consumer.mingle","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"mingle.py","line":49}}
{"time":"2024-02-06T13:29:05.139Z","msg":"celery@failover-api-7d57484775-88b45 ready.","pid":1,"tid":139976654377216,"pri":"INFO","tname":"MainThread","subsys":"celery.apps.worker","host":"failover-api-7d57484775-88b45","pname":"failover-celery","file":{"name":"worker.py","line":176}}
